name: Tests and Code Coverage
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  run-codecov:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup the Node environment
        run: bash setup/setup_dependencies.sh

      - name: Run Jest tests
        run: npm test

      - name: Upload exact version(s) of packages used
        uses: actions/upload-artifact@v4
        with:
          name: versions-results
          path: |
            package-lock.json
            ./coverage/coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
          flags: unit
          fail_ci_if_error: ${{ github.repository == 'e-mission/e-mission-phone' }}
          
